// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3JPU679Zzi-12uiBsBt6VorUv5Fn-9Og',
    appId: '1:1054047692408:web:18f8d3434caaab60576f8d',
    messagingSenderId: '1054047692408',
    projectId: 'mashena-e39bd',
    authDomain: 'mashena-e39bd.firebaseapp.com',
    storageBucket: 'mashena-e39bd.firebasestorage.app',
    measurementId: 'G-BMX07FY07K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTPAC4d458mFIHxWbPngjuTHcSnOklFvI',
    appId: '1:1054047692408:android:94a6f8535ec63088576f8d',
    messagingSenderId: '1054047692408',
    projectId: 'mashena-e39bd',
    storageBucket: 'mashena-e39bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq-JzblK-j5wXE1VWn29XZOFw-IM_fzz0',
    appId: '1:1054047692408:ios:5625ff46058281d0576f8d',
    messagingSenderId: '1054047692408',
    projectId: 'mashena-e39bd',
    storageBucket: 'mashena-e39bd.firebasestorage.app',
    iosBundleId: 'com.example.mashenaDriverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq-JzblK-j5wXE1VWn29XZOFw-IM_fzz0',
    appId: '1:1054047692408:ios:5625ff46058281d0576f8d',
    messagingSenderId: '1054047692408',
    projectId: 'mashena-e39bd',
    storageBucket: 'mashena-e39bd.firebasestorage.app',
    iosBundleId: 'com.example.mashenaDriverApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3JPU679Zzi-12uiBsBt6VorUv5Fn-9Og',
    appId: '1:1054047692408:web:82f1fe197870845c576f8d',
    messagingSenderId: '1054047692408',
    projectId: 'mashena-e39bd',
    authDomain: 'mashena-e39bd.firebaseapp.com',
    storageBucket: 'mashena-e39bd.firebasestorage.app',
    measurementId: 'G-JC1CDBR0Q9',
  );
}
